# Create local environment:
# { /usr/local/bin/ }docker compose -f { /path/to }/prompt-test/prompt-api/docker-compose.yml -p prompt-api up -d
#
# Run in case you would like to test functionality using any sort of client app, Swagger UI or Postman.
# Otherwise, no need to run these commands.
# docker exec -it { localstack CONTAINERID } /bin/bash
# awslocal sqs create-queue --queue-name prompt_results_to_store
# awslocal sqs create-queue --queue-name prompt_results_to_delete
version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: prompt-api-localstack
    restart: unless-stopped
    ports:
      - ${LOCALSTACK_PORTS_1}:${LOCALSTACK_PORTS_1}
      - ${LOCALSTACK_PORTS_2}:${LOCALSTACK_PORTS_2}
    environment:
      - SERVICES=${LOCALSTACK_ENV_SERVICES}
      - DEBUG=${LOCALSTACK_ENV_DEBUG}
      - DATA_DIR=${LOCALSTACK_ENV_DATA_DIR}
      - PORT_WEB_UI=${LOCALSTACK_ENV_PORT_WEB_UI}
    volumes:
      - localstack_volume:${LOCALSTACK_VOLUME}

  redis:
    image: redis:7.4.0
    container_name: prompt-api-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  localstack_volume:
